### ISSUE TITLE
Issue and verify signed JWTs with filesystem scopes

### ISSUE THREAD

**Issue by jbasney** [scitokens/scitokens-java#1]
Our first SciTokens milestone is to issue and verify signed JWTs with filesystem scopes. For the signed JWTs, I think we want "self-encoded access tokens" (https://github.com/ncsa/OA4MP/issues/6). For the filesystem scopes, see https://github.com/scitokens/scitokens.github.io/pull/1.

**Comment by jjg-123** [comment]
Done and deployed.
